apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-hands-on-2
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: IfNotPresent
        image: harry2680/frontend-k8s-hands-on-2:v1
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on-2
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80